name: 'Broken URLs in Code'
description: 'Scan for broken URLs in your code'
author: 'RazCodev @ Permit.io'
inputs:
  directory:
    required: true
    description: 'Directory to scan'
    default: '.'
  files-globe:
    required: true
    description: 'Regex to match files to scan'
    default: '**/*'
  url-regex:
    required: true
    description: 'Regex to match URLs to scan'
    default: 'https?://[^\\s/$.?#].[^\\s]*'
runs:
  using: 'node16'
  main: 'dist/index.js'
