name: 'Broken URLs in Code'
description: 'Scan for broken URLs in your code'
author: 'RazCodev @ Permit.io'
inputs:
  files-rgex:
    required: true
    description: 'Regex to match files to scan'
    default: '**/*'
  urls-regex:
    required: true
    description: 'Regex to match URLs to scan'
    default: 'https?://[^\\s/$.?#].[^\\s]*'
runs:
  using: 'node16'
  main: 'dist/index.js'
